server:
  port: 8083
spring:
  application:
    name: hotels-service
  cloud:
    config:
      uri: http://localhost:8888
  cloud:
    config:
      discovery:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
